drop table OBJTYPE CASCADE CONSTRAINTS;
drop table ATTRTYPE CASCADE CONSTRAINTS;
drop table OBJECTS CASCADE CONSTRAINTS;
drop table ATTRIBUTES CASCADE CONSTRAINTS;
drop table OBJREFERENCE CASCADE CONSTRAINTS;

-- Таблица описаний объектных типов
CREATE TABLE OBJTYPE
  (
    OBJECT_TYPE_ID NUMBER(20) NOT NULL ENABLE,
    PARENT_ID      NUMBER(20),
    CODE           VARCHAR2(20) NOT NULL UNIQUE,
    NAME           VARCHAR2(200 BYTE),
    DESCRIPTION    VARCHAR2(1000 BYTE),
    CONSTRAINT CON_OBJECT_TYPE_ID PRIMARY KEY (OBJECT_TYPE_ID),
    CONSTRAINT CON_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID) ON DELETE CASCADE ENABLE
  );

  -- Таблица описаний атрибутных типов
CREATE TABLE ATTRTYPE (
    ATTR_ID      		NUMBER(20) NOT NULL,
    OBJECT_TYPE_ID 		NUMBER(20) NOT NULL,
	OBJECT_TYPE_ID_REF 	NUMBER(20),
    CODE         		VARCHAR2(20),
    NAME         		VARCHAR2(200 BYTE),
    CONSTRAINT CON_ATTR_ID PRIMARY KEY (ATTR_ID),
    CONSTRAINT CON_ATTR_OBJECT_TYPE_ID FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID),
	CONSTRAINT CON_ATTR_OBJECT_TYPE_ID_REF FOREIGN KEY (OBJECT_TYPE_ID_REF) REFERENCES OBJTYPE (OBJECT_TYPE_ID)
);

-- Таблица описаний экземпляров объектов
CREATE TABLE OBJECTS (
    OBJECT_ID      NUMBER(20) NOT NULL,
    PARENT_ID      NUMBER(20),
    OBJECT_TYPE_ID NUMBER(20) NOT NULL,
    NAME           VARCHAR2(2000 BYTE),
    DESCRIPTION    VARCHAR2(4000 BYTE),
    CONSTRAINT CON_OBJECTS_ID PRIMARY KEY (OBJECT_ID),
    CONSTRAINT CON_PARENTS_ID FOREIGN KEY (PARENT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE DEFERRABLE,
    CONSTRAINT CON_OBJ_TYPE_ID FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID)
);

-- Таблица описаний значений атрибутов экземпляров объектов
CREATE TABLE ATTRIBUTES
  (
    ATTR_ID    NUMBER(20) NOT NULL,
    OBJECT_ID  NUMBER(20) NOT NULL,
    VALUE      VARCHAR2(4000 BYTE),
    DATE_VALUE DATE,
	CONSTRAINT CON_ATTRIBUTES_PK PRIMARY KEY (ATTR_ID,OBJECT_ID),
    CONSTRAINT CON_AOBJECT_ID FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT CON_AATTR_ID FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID) ON DELETE CASCADE
  );  

-- Таблица описаний связей "простая ассоциация" между экземплярами объектов
CREATE TABLE OBJREFERENCE
  (
    ATTR_ID   NUMBER(20) NOT NULL,
    REFERENCE NUMBER(20) NOT NULL,
    OBJECT_ID NUMBER(20) NOT NULL,
	CONSTRAINT CON_OBJREFERENCE_PK PRIMARY KEY (ATTR_ID,REFERENCE,OBJECT_ID),
    CONSTRAINT CON_REFERENCE FOREIGN KEY (REFERENCE) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT CON_ROBJECT_ID FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT CON_RATTR_ID FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID) ON DELETE CASCADE
  );
  
  
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (1, NULL, 'USER', 'Пользователь', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (2, NULL, 'ABSTRACT_ITEM', 'Абстрактный класс', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (3, 2, 'PROJECT', 'Проект', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (4, 2, 'MODULE', 'Модуль', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (5, 2, 'TASK', 'Задача', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (6, NULL, 'TASK_LOG', 'Лог задачи', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (7, NULL, 'ROLE_LIST', 'Лист ролей', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (8, NULL, 'ROLE_ITEM', 'Роль', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (9, NULL, 'CONTACT_LIST', 'Лист контактов', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (10, NULL, 'CONTACT_ITEM', 'Контакт', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (11, NULL, 'DOCUMENT_LIST', 'Лист документов', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (12, NULL, 'DOCUMENT_ITEM', 'Документ', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (13, NULL, 'DOC_TYPE_LIST', 'Лист типов документов', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (14, NULL, 'DOC_TYPE_ITEM', 'Тип документа', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (15, NULL, 'STATUS_LIST', 'Лист статусов', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (16, NULL, 'STATUS_ITEM', 'Статус', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (17, NULL, 'CHANGE_TYPE_LIST', 'Лист типов изменений', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (18, NULL, 'CHANGE_TYPE_ITEM', 'Тип изменения', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (19, NULL, 'COMMENT_LIST', 'Лист комментариев', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (20, NULL, 'COMMENT_ITEM', 'Комментарий', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (21, NULL, 'PHONE_LIST', 'Лист телефонов', NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION) VALUES (22, NULL, 'PHONE_ITEM', 'Телефон', NULL);

-- Атрибуты для User
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (1, 1, NULL, 'USR_LOGIN', 'Логин');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (2, 1, NULL, 'USR_PASSWORD', 'Пароль');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (3, 1, 8, 'USR_ROLES', 'Роль');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (4, 1, NULL, 'USR_REG_DATE', 'Дата регистрации');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (5, 1, 10, 'USR_CONTACTS', 'Контакты');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (6, 1, NULL, 'USR_COMPANY_NAME', 'Название компании'); 
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (65, 1, NULL, 'NAME', 'Имя'); 
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (66, 1, NULL, 'EMAIL', 'Почта');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (67, 1, NULL, 'PHOTO', 'Фото');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (68, 1, 22, 'PHONE', 'Телефоны'); 

-- Атрибуты для AbstractItem
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (7, 2, NULL, 'AIT_NAME', 'Имя');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (8, 2, NULL, 'AIT_CREATOR', 'Создатель');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (9, 2, NULL, 'AIT_CREATE_DATE', 'Дата создания');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (10, 2, NULL, 'AIT_DESCRIPTION', 'Описание');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (11, 2, 16, 'AIT_STATUS', 'Статус');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (12, 2, NULL, 'AIT_DEADLINE_DATE', 'Дэдлайн');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (13, 2, NULL, 'AIT_COMPLETE_DATE', 'Дата завершения');  

-- Атрибуты для Project
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (14, 3, NULL, 'PRJ_PRICE', 'Цена');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (15, 3, 12, 'PRJ_DOCUMENTS', 'Документы');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (16, 3, 4, 'PRJ_MODULES', 'Модули');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (17, 3, 1, 'PRJ_ASSIGN_PMS', 'ProjectManagers');  

-- Атрибуты для Module
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (18, 4, 1, 'MDL_ASSIGN_TM', 'TeamLeads');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (19, 4, 5, 'MDL_TASKS', 'Задачи');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (20, 4, NULL, 'MDL_PRIORITY', 'Приоритет');  

-- Атрибуты для Task
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (21, 5, NULL, 'TSK_ASSIGN_USER', 'Developer');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (22, 5, NULL, 'TSK_PRIORITY', 'Приоритет');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (23, 5, 1, 'TSK_WATCHERS', 'Watchers');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (24, 5, 20, 'TSK_COMMENTS', 'Комментарии');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (25, 5, NULL, 'TSK_PARENT_TASK', 'Родительская таска');  

-- Атрибуты для TaskLog
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (26, 6, NULL, 'TLG_CHANGER', 'Юзер изменивший таску');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (27, 6, NULL, 'TLG_CHANGE_DATE', 'Дата изменения');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (28, 6, NULL, 'TLG_OLD_VALUE', 'Старое значение');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (29, 6, NULL, 'TLG_NEW_VALUE', 'Новое значение');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (30, 6, 18, 'TLG_CHANGE_TYPE', 'Тип изменения');  

-- Атрибуты для ROLE_LIST
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (31, 7, NULL, 'LRL_NAME', 'Название');  

-- Атрибуты для ROLE_ITEM
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (32, 8, 7, 'IRL_CONSIST', 'Состоят');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (33, 8, NULL, 'IRL_VALUE', 'Значение');  

-- Атрибуты для CONTACT_LIST
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (34, 9, NULL, 'LCN_NAME', 'Название');  

-- Атрибуты для CONTACT_ITEM
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (35, 10, 9, 'ICN_CONSIST', 'Состоят');
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (36, 10, NULL, 'ICN_NAME', 'Имя');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (37, 10, NULL, 'ICN_EMAIL', 'Почта');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (38, 10, NULL, 'ICN_PHOTO', 'Фото');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (39, 10, 22, 'ICN_PHONE', 'Телефоны');  
  
-- Атрибуты для DOCUMENT_LIST
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (40, 11, NULL, 'LDC_NAME', 'Название');  

-- Атрибуты для DOCUMENT_ITEM
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (41, 12, 11, 'IDC_CONSIST', 'Состоят');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (42, 12, NULL, 'IDC_NAME', 'Название');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (43, 12, NULL, 'IDC_ADD_DATE', 'Дата добавления');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (44, 12, NULL, 'IDC_DESCRIPTION', 'Описание');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (45, 12, 14, 'IDC_TYPE', 'Тип документа');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (46, 12, NULL, 'IDC_FILE', 'Файл');  

-- Атрибуты для DOC_TYPE_LIST
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (47, 13, NULL, 'LDT_NAME', 'Название');  

-- Атрибуты для DOC_TYPE_ITEM
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (48, 14, 13, 'IDT_CONSIST', 'Состоят');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (49, 14, NULL, 'IDT_VALUE', 'Значение');  

-- Атрибуты для STATUS_LIST
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (50, 15, NULL, 'LST_NAME', 'Название');  

-- Атрибуты для STATUS_ITEM
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (51, 16, 15, 'IST_CONSIST', 'Состоят');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (52, 16, NULL, 'IST_VALUE', 'Значение');  

-- Атрибуты для CHANGE_TYPE_LIST
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (53, 17, NULL, 'LCT_NAME', 'Название');  

-- Атрибуты для CHANGE_TYPE_ITEM
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (54, 18, 17, 'ICT_CONSIST', 'Состоят');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (55, 18, NULL, 'ICT_VALUE', 'Значение'); 

-- Атрибуты для COMMENT_LIST
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (56, 19, NULL, 'LCM_NAME', 'Название');  

-- Атрибуты для COMMENT_ITEM
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (57, 20, 19, 'ICM_CONSIST', 'Состоят');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (58, 20, NULL, 'ICM_AUTHOR', 'Автор'); 
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (59, 20, NULL, 'ICM_ADD_DATE', 'Дата добавления'); 
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (60, 20, NULL, 'ICM_MESSAGE', 'Сообщение'); 
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (61, 20, NULL, 'ICM_PARENT_COMMENT', 'Родительский комментарий'); 

-- Атрибуты для PHONE_LIST
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (62, 21, NULL, 'LPN_NAME', 'Название');  

-- Атрибуты для PHONE_ITEM
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (63, 22, 21, 'IPN_CONSIST', 'Состоят');  
INSERT INTO ATTRTYPE (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) VALUES (64, 22, NULL, 'IPN_VALUE', 'Значение'); 

COMMIT;
