INSERT ALL 
  INTO OBJREFERENCE(ATTR_ID, OBJECT_ID, REFERENCE) 
    VALUES (TSK_WATCHERS, 159, 23) 
  INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, 
    VALUE, DATE_VALUE) VALUES (TSK_PRIORITY, 159, '4', null ) 
  INTO OBJREFERENCE(ATTR_ID, OBJECT_ID, REFERENCE) 
    VALUES (TSK_ASSIGN_USER, 159, 39) 
  INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE) 
    VALUES (AIT_DEADLINE_DATE, 159, 'null', ? ) 
  INTO OBJREFERENCE(ATTR_ID, OBJECT_ID, REFERENCE) 
    VALUES (AIT_STATUS, 159, 16) 
  INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE) 
    VALUES (AIT_DESCRIPTION, 159, 'Second task for Module 1', null ) 
  INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE) 
    VALUES (AIT_CREATE_DATE, 159, 'null', ? ) 
  INTO OBJREFERENCE(ATTR_ID, OBJECT_ID, REFERENCE) 
    VALUES (AIT_CREATOR, 159, 26) 
  INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE) 
    VALUES (AIT_NAME, 159, 'Task 2 Name. Project 1', null ) 
SELECT * 
FROM (SELECT ATTR_ID, CODE FROM ATTRTYPE) PIVOT (MAX(ATTR_ID) FOR CODE IN (
    'TSK_PRIORITY' TSK_PRIORITY,
    'AIT_DESCRIPTION' AIT_DESCRIPTION,
    'TSK_WATCHERS' TSK_WATCHERS,
    'AIT_NAME' AIT_NAME,
    'AIT_STATUS' AIT_STATUS,
    'AIT_CREATOR' AIT_CREATOR,
    'TSK_ASSIGN_USER' TSK_ASSIGN_USER,
    'AIT_DEADLINE_DATE' AIT_DEADLINE_DATE,
    'AIT_CREATE_DATE' AIT_CREATE_DATE)
    );