SELECT ATYPE.CODE,ATTS.VALUE, ATTS.DATE_VALUE, OBJR.REFERENCE
FROM ATTRTYPE ATYPE
  LEFT JOIN ATTRIBUTES ATTS ON (ATTS.ATTR_ID = ATYPE.ATTR_ID AND ATTS.OBJECT_ID = 77)
  LEFT JOIN OBJREFERENCE OBJR ON (OBJR.ATTR_ID = ATYPE.ATTR_ID AND OBJR.OBJECT_ID = 77)
WHERE ATYPE.OBJECT_TYPE_ID IN
      (
        SELECT OBT.OBJECT_TYPE_ID
        FROM OBJTYPE OBT
        START WITH OBT.OBJECT_TYPE_ID =
                   (
                     SELECT OBJECT_TYPE_ID
                     FROM OBJECTS
                     WHERE OBJECT_ID = 77
                   )
        CONNECT BY PRIOR OBT.PARENT_ID = OBT.OBJECT_TYPE_ID
      )
      AND (ATTS.VALUE IS NOT NULL
           OR ATTS.DATE_VALUE IS NOT NULL
           OR OBJR.REFERENCE IS NOT NULL);